---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgB9qY7MhYuUOP9t9DJLiEg995oJkK1dYadrPYmF4gQW8SyfGI3GxIFRLTuJLWkcRk5UWgwu5PIHd5Y4jni+nnCQ6f5OichdXah0XcjRML/j4gULDyOYa0gF83Sik/oVkjA9WeTQ75OSPBtQA6Rv1U8DJz0+cSuDbjpQOICUlO/ugmAEyXHwEnHEag7PJ14FyyxQe+N25xVmct4YZbdRAt/wLao/SPgn72T74Am853IyfpPPSq8jeXHBqSTDGqRF20Lg7mWuphn7lgZx1lZKFetfSuIdcKEJ3b2djF3WhrDED1GrSRlgzkmp/1GlN4duFZ5Y34M4uimbKBnNDZHx9FyZ4poF2i0p8TbtC26iewjnFKkq8LWqJGiPNHZshb+ai1UN0SVq58pYZuGfZ/wyVebe6ScFjbHmklHsJqNi4Mu55Jsu2UqJIwqKT6spCPjwgQ5B9JBKnTCnbgFS9+mJjymsxSeCEZMSOwdbQdaQXGIX7XwLrhlhoefXwsd8VyDdMeZM0j19Cl5/J7B34JqKvPAVL5/GQxYUicDW++mUiyLatxa/rWN31IlaLJVz3HRjbQC6HJNTzS5sgYIoS5p/P2JZVywPlmmpKi71AtZyVTkJ8nKl/oWjNKG3NNOJ5tUfcszPHrcH2+sbqnxY2dwuTRea5zH/mFsAGWKqo1qeiY+3Tzgwaww2cUfZ+R88yWWvPPir6UzFCcK9qoa5QW5QiT5JNqIgfIMWtokfa0JNCY7xlLFoNP71rrpGKu1LX3072th9M7EpQbKDBLhzIfu8sfo5
  template:
    metadata:
      name: vaultwarden-admin
      namespace: vaultwarden
