---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-backup-s3
  namespace: vaultwarden
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAJcCukm4cfeOpI58dFlkDgbJgYHOiDFSJcSOJ2nbVaic8jUJZxd8K7f6i6rWqwZAXl++6Yd0BFv39Vq48Y7DUV7xE3LceRP8v21p1MhyZWtd3liR2M+dH3yPaCNhOSaioaZy+G1XS+bAD6PQwvAlE91uarAqRmeBAoZXgwcDUmXpXTUDlcORFfJee+hwxOF9Z/RkajBp9CQuvawlsPSeGhD0lmprync37z8BvJE7BsnZGbyHvs1xM+knTZgKfi3mlyRpR+EFRdh68ZncD4nQUlJhDmMI4kN37jR2K9UFGAbNCe4kG83hc9u+tDFy1KxH2r6m36dNLfa6VkIY+riJzcsJu5SdO+71Y6bqSycQ57YSdOwNZLr6RlVz/GKzHDueh2C4iNX8YDd0DiTEeHMjnUYjIZGlKqwEO28Q1GEgPpzjm9s/CYtlkG5v+q9yXxx6gH4THaRmb+c0KwpHPYO0vSA8ao5bq3mSR89JZF43SJwogst2uXixQCqIlqNOCLddC/u04+hw8be1wVSt0bU04lpv+We+8mRfgud5M0Spks4DM2fSM2nI7gz08rE4iZEZUZxIP1ufpOHwdx9bRv0S74XSovz4HFTrM7pIM5MQ/VmF1gOVlwqL9aJk/yY60FOp+zJHBmZiBo7PhfEQPfZP8lDQ3IeRyJ5JwPLt1zMiUjfDcoUK5uR0RdkuPS8wAigMp8CBcIdlRZQ49Rpn9RpPTISMRDzQ==
    SECRET_ACCESS_KEY: AgBtKkRPFoqspoiJc2vv49I89jmOyJZ9A37cMM/Ljl9Vts69lOqnHvWEcg6iLbY9QYMlUvVoVkcWbY56bq+7mVtqoDz65+E+cgVjQz5W6q8KGxQa9qX647KG/egnLGmcb27UBpPNJ+HE4mvrsXuAsPtRtKP0N7vLUF/TIT1kJuXn8jOi3uV2W2sPGz+SNCqjiktZAEiQUCj2iXFnnvgdnPuwdLefTZBPdLTt613gbzUR5yeS4AsMQC6ddHp6bkf/Ht56eiGlScG7eUg7Fyt8dQe1P0n8QHZCvcqfJuCD0jvkaQuiSv8OG8g9/AMzcn+yGvMrML30ESm5ILrthMNVsAINcmDTUbMLK0TalkZBPb8e01dIFjR7mdd1S+bm3SkHQT/MHmPGI/Z58FCOWBLtjwfcOqBNh9oYVmUccRC2fEYWXYb368Y8Vby8JhAJd4nvURAy4h4m9OTFhL8mf0YVk+o9MszHdLrva+WAGSvdqNHCbPOEoVXLKdqcoC+yhEoSj+xizZnrxyseu52cxA6pp0OdG6VHqgmKvz3Qv/DfP22Ru4r3SwW9fBldJBvtMPscroNeRCncpP1xqQiklBpvi2NQkJehKvpPsJREuM1ipvtA+e6/tuOQiT6/syjuxVGm5Rj1zTyAo17Th1gxXFp4NK1i0CTRAPdWrZx/AQfSqXgWj4Sf+w5jMu4sClaNCOgU1n1lY+PldrQQkaepK0FMEqbKODdmo6ICu0nsYSYo7buL4bbCW9D6tAhH
  template:
    metadata:
      name: vaultwarden-backup-s3
      namespace: vaultwarden
