---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-smtp-secret
  namespace: vaultwarden
spec:
  encryptedData:
    SMTP_PASSWORD: AgCCMOIEAbK1WmRt/sQJF2I+PaesMJ5+k6Ha3QbCHXv1cVQyHErXLgHewrqbRzu8UNGQXRZ/aBlJTeUnqScG9bYYQcCrl0vUz32w68SBC51tdVhbv4Wy77jnSC6esqBiWeaKX/a4vcjL3FRqJXJq09jPBSBOgr6kmqgUIV7DQ2ePKrCi9rcb0AIHcu7c2IChYSHF/ekV9GOjkF4D2CLUcPTH5N5z1mX3iocDI8ZBWSDQZ1JSrhkVCUnJCYTMy1qe6RWCqkokqd8AumEXdUg9c1ummk2wyMZXm2Hwwc8TqkBNmc4INFiN1BWR5ReHUf0Iq9w9QQNzK1wHAqUKjYDoMwW0bDT818pU2xZ8vKtozbrcAC30ovWWVuqLOrgPDXzT6RLv0iEo0rT38NpQ7ZC4ycvCRaKSNEnW6DhZhOxk7TH/Hv6+b8jlS31gFReV3QJ5TNmv3dBw4YkxEWQ9YpzOWT5ACwVJQbLejjUg5UZG3X8BajCkGXiQ57nApg4y1iepTKDZqRXkT3HjhD0xmHvctV17FnsnadK33DN9rlhF2GZBSC5zaHXI27XqHQ8Z68DOH5TgI9v61juC7g0A73uWkelfR5lzyzsqjuyDJWKD3djzmaIzgQf2xCFycQnYjf3HCvHWuwyO78h1gGKcWoQYChyUogHp/blDe3OZNKaiRoolQkRE9XKkIAEMBWmEHxjjzQgYSU6ldEs2FV06362nE8t64PseqE4nR86A9poG7NU=
  template:
    metadata:
      name: vaultwarden-smtp-secret
      namespace: vaultwarden
