apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opnsense-exporter
  namespace: monitoring
  labels:
    app: opnsense-exporter
spec:
  endpoints:
    - port: metrics
      interval: 30s
  selector:
    matchLabels:
      app: opnsense-exporter
