apiVersion: v2
name: metrics-server-wrapper
description: A Helm chart wrapper for deploying Kubernetes Metrics Server
version: 1.0.0
dependencies:
  - name: metrics-server
    version: 3.13.1
    repository: https://kubernetes-sigs.github.io/metrics-server/
