---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
spec:
  encryptedData:
    CRYPTO_KEY_VALUE: AgBpJ1bvsuXzUl/BKx6ukB6AHTQHuz+S5kxnM6lDh1EI3l4Bz5rPQ3cf36TTfRUOB64JyqJjYXrOaVjgMvj0IZcDMT+YFhw4lzaX2NazQZZPaP7sk6VZ4MHNkeVW7ojd8a1i6tCdYfkXSzoK7usswkBvRtVX5uAjA9sPVdvvbCxCxn/GkASYHWhcIEBpmAMTSDPBHolajOv4hUh7XgxKtHCBkz2ADL7wlAkvxkQ98G5P9dCkjny/CXIQX8knKp6OMHtTK60QUMx2oRskGW5jLVLnr9C/rKRT7QJIWb6mt+DkyzyG46UG/R/Vagpkawu2MitC6OH29k2F+TbnAbkYl0U5DFB0TM07y9ryGEQHbvwwXdXufHLEz2kj74ca9TOBaflxi2VS7OEGkpVBnFNenh7m08QP/upw0vNF6uOBosJbPdykTDz9qAdjyJRM0h1kywJDUVW4NcxBjLniiPKl05GMHzdo5NS1Xizudpr+sH0t8eXNizB0all8AtOHkqphrEV2o6AVUufmXEbQ0HZ4TLRtWKfEMAlxPglxvcpEB0ICz3I7wCqBMd28z0UJRwYex8nUrCQ3EmJ7y6ut63HhNciQftLVcp2flqHU/8Jc1RzvOCEEzU/mUA57iYxLXr9hHHxvHrgWc74M3O4qOA35n+bn+NxsqmEF047h5i5exZqc/Bb/B8bYq/RamC5eqau2TAMzmVfY0GnC/5Kh95snzeap64aVTikvDC+9OzqrRi3WHx4uExFTG9UZ8VttUTG1MAw7PtRGxrd1YLh82pI=
  template:
    metadata:
      name: longhorn-crypto
      namespace: longhorn-system
