---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-crypto
  namespace: longhorn-system
spec:
  encryptedData:
    CRYPTO_KEY_VALUE: AgCb32JxnJJ7glE8rtC6ZKHn+j/VAmQKTo4m0WqtSJNXHgIc4tuo1OFDpgVSBvkLyJSFR5U5ZRC1/7rxqwCTsDQSzkhqvJZja/flC5x040owEeNdQ+8YOKRmW/H4iKjpzDiXBcEPT8zo3xBaKW76tpT9EWsMgwYRLLeJcHV4IYlpKPWoW3hXGlikMlh8gNCvbjeiABDCzQ99vWTuk1HMNOwDOiP2KQj1YmvCGLLZF2IQNQjPX5I7CyLIZCR1+o+2/FnObg2ZE5EqWL+T5eV6Yk/dSK9eq1SAXJ7sK12am6ZOFPFc09deaTAeAmDflaMRTM4oy2ANX59NGGI1xVeIhfMoY/cm+xb2zuQMP0BQo2F4R3rbpwVtCCucFuqz/H9foDy3Pvr6h1TMJ7KF+O6VzIhFQO76go6xql4mze6TSnib2/qCnI4J25XoOc25t5K27uV+BwdGtY4NcGys4uULNAEWEvRVsd3QTF9VbG3C18mkeKOUi4QcOTBStB3PpcjlJcV4DD7VkuKNF6vUxDYc7KmjeBnT2pHoswtccCr8iseL+Uffr+YK8anuG/5vT/SPvIbjnfu3QqV+JTBbp3vhFF7l1Vk0gr/Jymwjm1EAFbbzJP7Xp06KdIgE9Nsa78kI5T7lnAp2FhgUgNS9RVFgeGQ66xgKs4NjyQIKO+sw1om/07gdKI7mDvejlybOxDPtMGJwE30AHAfce3amepKZs/3f/fg+pWCtIzNzYg3HLK604HPK+/gwExLL2spq3g==
  template:
    metadata:
      name: longhorn-crypto
      namespace: longhorn-system
