---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
spec:
  encryptedData:
    password: AgAR9XBiWRH8oPaOugWfdQpAuGzN63oqC+DxsbFRWR1djwCjfGE5DTRSbdCXcPCAV8zEH9KLBeKLswC/O2nYqbPTOYsW5Wy60GzzA+DbCEft3s2hK2ySmp8s36yNB1dzL/aSdVZ3q6OhB9ohICa7WU5pvz7RsD0YZniKJInue+bNdjT4TBwhyKMN42P3d7LVAk/vdBH1IwPaXj0jYmqeTen0pSPonClClK1xqrjZ79K2fFweN8GT3gXzMcAWgsvsOOdFRjw+osfP04iztAMnqlc3UjevToYN0g30sMeor421gkWSYANxOcxziVjHBqMVQABjFHYDd9pmeyGihErYQYhqA4ugDK4ICP6VhHMnwKm2mjEc02OqHZTuLmDaSosJOaLEFU42zGpmFW4gf0a4IE4/3MHI7EDGWsk6Zj+a9Wntv+5Wvgd+UpTy5AoTq27OL59D0zFD8RXr5KQCWVyOEQAuXQNrefAF2RALhkgvMKfJa8+CzAU0Wsw5tmA1tJFcqME2WbgDPEtKsEGhJySt3AC0TwIHWUEyRsriJZJE4OOnayWP9b1+NVzfBUDwdoYQEYzJDj1gZutwpgv0ydNKovbJR93+tTbSs0y1UbhDFZH7d3nRDUbwvWSagNkC822h7r0TW1vTT1ePyP9kCkb2VrPl78au7a0Aeqzsvdsm7HTDphAZl+198n5veY1VtiOCOsqsjrwP776wNBMqBy6RO6Ba8UA+wyJEIWn6zdQZ6zSIDg==
    username: AgBn46SMJ1ojEhzxTb/iKBOFnEFgCch2oAsLSqm7Jq1Fbh+pFOnffs59LHWc7UGVF+toaf4EaGcWJQg3FO3J0vH7/6sLQ9s0d3Z2NXBoskdDE0ihz8kow64ex3etCD/jEZbtFd5sB17sLNDY8OWm+y0fktTiETxr9i/AF59EaH7sVNWlZoY4cB7ewbrHgiTcq5lxwVH8TliQbxLNTUg3vomYE3xrFucByQSkQw64pQPSPffbl+ah1qAnDAmMWo58BDV0tUqamSFrCpezlaHA9fjXI3CgACkaFEdyZImalZk1vhyKI2ExniJkpQHLsrURSN7WZMMPINw6PNg9GXsPxlp2geuZfdNTmIdfS5jR87HCmagYoroTImrQKIJkQsqVa73ztIe9/D1UMw9d91LMug/4N3W4xvJWdLcpM2nY+jcDm4k7HtlDWjhL+T6DjbZX/jPnWvMUK4UrjHLjFR6nA671bxh7BsMD7HJtk6J8taUkrNpi6krcicK4nNt6hxXdnDqlGNbnHzoZRw9IrkKZJZ4/Ri8SaK5lXT5mcdz6UHFlJtj0ybRA2HZ73/vpzeIcmhmftzPwUS4NR3kH9QInSbafSMO9Pm9sruGEzFIGnjsDQ43itPmUnF2SGkpGIjB/Mx9d9VrQe7caHrzRIgL6GcVU+G81KfM1I2R2WvUergwYClOp5FtG6C17UV3mnxxu8SSfOg/obKXbfw==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak
