---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-config
  namespace: monitoring
spec:
  encryptedData:
    pve.yml: AgAheQnlyFqrluFYjfwnDeMzW7HmDYF5WMrk8nOMj4cnJmW3999eIe2+o4L5Wy1fWPR5TJ6IMsPKL0FPwZyB7sAhmGbMZ5aB93P3SHJlYDanCa3yygpYQ9NFFRIWk8vubRNWrRIWgfpyyhhNfFXPUD24HGruQ5AgFmKLasVFdGn4RmqP3NA5yhO6PFi3Tv9ip6S2SRIHXP3f0cq3yb7HqoK9NNyPAQyb2chN8QiMAN3+lfZKkLctWsUeWAAz8ZBCmUA+PURPl6ugVN5Dh9do7xKGT8T18xzEOlIE7U5iivaO0UDiXkqEgcOuToDvU5E+m62xcPYzbA7iOROQoZodTSLFmEf7sUgsy7E2PHLCZH+dhpeBDvEm4QapWoOKmWsgkl1CHCzGCfdymgmFzEoLxAUGPU/Frv2tMo+bxyCn21mM3rfFeWvWnLq6toJK5D3Lmkve6Ryby4zv6W5e2/mR2ppZ9y7anz6rSkiAvF68iAikmExJRnnNS948AY3oTxTGaDlutKZeycu6MjBUGm0GEd9JsW43oW4jGS03Oe+qpdS3bpdzZlxlWU/YqS1P4qI5qBOJZKWfGHmNWe7XaYLDWfRA2ctLAueRjB6NUGR+ZUWAGCwjbuhO5s7/NkyROLTmgx+c6Q+llzib8z3ujVipCphv+oI5hLGU8Ngdc2siOgtphnrBa5uANugDYg/iawxnOE7ANsIks8O1BZXd+OurMrIPmd+RLJTk6U4b3bes3ptqpGk8hhqpd7jqUnS4/jV4noRiA1ziDchVmiZODVRGwbjLSwDEgJp9gMexYCwGwCdRgV6PPyPMy+GW+TxSYxNOzxSQQ850KnIcPCYSFli/wF+W/tmAksmdEoUTFxgnKuN8+g==
  template:
    metadata:
      name: proxmox-config
      namespace: monitoring
