apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app: proxmox-exporter
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /pve
      interval: 30s
      params:
        target:
          - "neo.mracek.dev"
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
  selector:
    matchLabels:
      app: proxmox-exporter
