---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-secrets
  namespace: vikunja
spec:
  encryptedData:
    jwt-secret: AgB94mGbJvIL87ZbSX97ogL28Ym+4FQIu2B+YbFiQ60TlUmiQx/ezsq641v0FG4jEj7r8lp1R8r3z2Do92ezqSSXN1fMyP8Lj739k/Zt7D+HhJc6tc2FfImugIJ6Bn7dcevX85WuVMQ+tgFAIPq8bgwA7SYNkaZnOUgyBm6aWadF+lpfyDwxp75euRUhhkvt5dp1OsCMj/Epi8dy0kW6erkNkrGB8xo5akbMn4TZpoU4lXZGBmAQ4IzW0xvO1+TLNX6WtijR3y//kPZ9Rapqi7UHwopP0eP+N8Cs91GGNj4fQnisMIuAu4qIn74S/UNpPD5zCayp36uCyPUd3ViOEFEJo9yi2hVWdWJJc6D2roxSbtMFIGHmnd9xLkPHGblxZ/J71zimyhBzyR6E+wQDt9UsZCGfaP6KF/OEcYtSJ0qD8u8eqTiLKLEpwSpCQMMyDwStxCgNs0jpm5EDKD3bes8LB1+hhHju7HznubCsa9xcbbKviYQuEw9PajcXOBKE1ohwwjqKguB1IIclZ419j3C6Pw2oPF+ph+mnGRvvEtgQCtsbh2iudPU8RAfLZMl3p7Q8I8rlKcn27+rPAU3WhSZt+hJ/RD4LnmbMYxxHEdRg8T22fSPjwIwFJbePKdE2jOLuPmGvCeeuhC2i1nb0eVbUbMJLAIyuAbhpIRiQWaUsnT8OublSJ7ZFuRDFgmvqUk9shzpzGVJN4zq2u7BALy0BJUOwddSHo4khOdcTbDg7TgGwd20fVhot0BwTlUVaplFp6rIjQlF4IdSKRvSXuwQK
  template:
    metadata:
      name: vikunja-secrets
      namespace: vikunja
