---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-db-user-secret
  namespace: vikunja
spec:
  encryptedData:
    password: AgChroiPpwg0FFq0OsJjoLu6PL+9/Oo90+43Zuc9lmMjowqrbs7toZRRQdWx/aPH4p3B7Ze/GJ5VPEPsHqP+IhwOrYFHZZlFaZDNxKO4Rz4cjlGgGml/6xo4xTO1MB38Cl8A7D1guV5wuOpfKQDKa08jr9/wfHVOqoSp9X96Xt/H4yNgQi8yTSFy3bwiq4w0MKQK069Pl01D27Uv/Z2y9mu0pRwFDIlqqclmResEtmbg4nMV6vB8dMaap1TeFG9PhA2T8ELqpXD+76rTv/6fIcc2t1UJGsTFRtL3ju9iXXFZ2HCstHXWa1W4pacpKKIC1OW/hvUGt8L1ZpM823bMDtuL5g5dUZJM4+5fnNY0LQ20a+iEvqRN+4U+RLvrEGLKEG2WFQKaI30LOineTptYSQk1e9wytU4Vg3YCkQfqu4jxBQmUASMPweCgdZHsO98eoLeLNCKGzCmwG3pUj/su2EyxMcvlTfHElvpvzmCx7IVjgFJwq2GENofP1AL+z/bAxJT1wsH+PenpcyYNoUgZg5nIjDvRxEq9hPibABte+cOHnHzgYJG9/dAcqZZucn0tMDfU/RyQgzD2mWAx14LWrwTIzW2OuI706VF4cGsdfu1JkMUgwHNg+ML8Xd6Bpv946xiOvHa0gs5TTrJK0Ggjnhpx+EmpGTNy5H44q3TzPwl4puN1ooClQ/JJo2fmilbdLFVTAHmzdgGAe/KOoCjS4ylBBYNOnB/yuWnJ/rDu2uQ1Wqa4q7XxKW2sm1NU7A==
    username: AgAQK+BHOTYYOW7nmkuXgSYRdECxAn0MoMXAcTHgLJ2OGdA4J1SFCu+isgyvWfQZ67UyDAN/BkGIyx54F+uHiHydxHINMLgWj9nidEDt74x+aDe5N74ik8GZt0jLWUEaxt6RGQkgrsdkAqkms9MS3iD/CA1Rcw7ti24bjDlpb50HSxyVDHdfx8WaArG4vL1gSnOaEIURY9yvTpRX3HNThw8rAmHVd/vTIKaBoep/paHTYHt6YHGTLqWcVpDucNTJGbtzTmvP2eGDW02q8g05lqqseYwdPXjdyAcWOJVCniavfFOfb5wE5gHBmZp3ts20got8N6ikeW4Lvuh4uVknaQVHFP3alSzAH0afJfrPY1pKL08EpAcfQ2X7A43QGpSndUAavzgN4Lf+zSWooSOtzad/WIClYvU+A3UFDDqMJe+xN442V3Zvgi516XIEvi6fLI39wSjkXTLuerkPwCLDe3oNISAcpi29mWw699IPP5DYCR4Uhdh74/pu+bz3crVwdPNcn5I3mr4WNzLFWB1mjmLQec54gCy+N/7f9kDpyHI1zMBGoyA6952V5xWxV2KX9EK6vvA68S0Wt4S8FsqmzlYZvKNorCZofiaQBSufMwpHgRWGp9b+2jztotXA2UBnEbaNtqd8rwQzKts9sC6GeAJMvbETOWwu3IFzZmvbWT2/bTqOp4t62IM9vgru/b993rRVEvCUi9TH
  template:
    metadata:
      name: vikunja-db-user-secret
      namespace: vikunja
