apiVersion: batch/v1
kind: Job
metadata:
  name: n8n-db-password-sync
  namespace: n8n
  annotations:
    # Tento hook zajistí, že se job spustí při synchronizaci v ArgoCD
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: psql-patch
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              echo "Připojuji se k DB jako superuser a měním heslo pro uživatele n8n..."
              PGPASSWORD=$SUPERUSER_PASSWORD psql -h n8n-db-encrypted-rw -U postgres -d n8n -c "ALTER USER n8n WITH PASSWORD '$NEW_PASSWORD';"
          env:
            - name: SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-db-encrypted-superuser
                  key: password
            - name: NEW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-db-encrypted-user-secret
                  key: password
      restartPolicy: OnFailure
  backoffLimit: 3
