apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
spec:
  instances: 3
  
  bootstrap:
    initdb:
      database: n8n
      owner: n8n

  storage:
    size: {{ .Values.db.storageSize }}

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      effective_cache_size: "768MB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://mracek-k8s/n8n-backups/
      endpointURL: https://fsn1.your-objectstorage.com
      wal:
        compression: gzip
      s3Credentials:
        accessKeyId:
          name: n8n-backup-s3
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: n8n-backup-s3
          key: SECRET_ACCESS_KEY
