---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-crypto
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    CRYPTO_KEY_VALUE: AgASdxB5MT6+roKerkTbyoUe5RfnDMTzIkg2Ec2AnqySNflFCzTBbCp6l837FymXGHiNQ1KGL0/Cvegb20r5am+6EgPPwlGuhso3w8EfitFAjOLUy3fD6ZHPKEmAwc4TAz6jEx/NcncQ6mR9liistQtPpnqtIYHi8YDgNWdjnPepIuALbTz5wm73on9pP6m9QaBFVQDhBrZ0QEnmj1Nnz7z3sebh0Dm1im1dBmWsQQGOWKuq+RpLOkCh1Df/JYpohfbIVG4f+Wo3VWLbocMQ3sNcVlgs49hMyJdKvBs9XBFwscjgF5sfI5ze4F68nx+/MHvY0Wj3JZf9iM19GZfWLTTePzdHZcFXQQrTmMCdax5jT/E2j/rU0mEMafZC9xYp7q1Q4qxmkEU+rO+kgY/KCnAWqibtCL5BYI3gajPdrkppFk6+85l10txWQc64VgOWaNVt+hR3iOxKD+1ApAWKjb0sr1N5ZZdBPH7ZsL0TUypt95GcUmWFi1iYhq6vo5brsLGiGIKF05S2YAmIAB81ra2QoSSaHy7Y1RMOjW7pk+6YW3CDj9jWEnoI77s5/Sg+p6agm+2yVmQvTSJi/goWhCp/nVR01wL3gnIY/1tbYrL4xFGT2+arBuH0B87KPQdAzbi5SFQ5x1qW8T+Pph5x/2DW2FrDFKZxQKJy/SuT66MQmQ/vvNbFgENmhu147vzgI47hIwxv8ZcyeX54iVfd/1xiqvVqrjQYg/3WcR+SBv7UsaXNNiODuNw70TIZBZ4mDc8uU8Df0DneqKpDnuc=
  template:
    metadata:
      name: longhorn-crypto
      namespace: {{ .Release.Namespace }}
