apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: n8n-db-manual-backup-1
  # Změň na namespace, kde ti běží tvá původní databáze:
  namespace: n8n
spec:
  cluster:
    # Zde musí být přesné jméno tvého PŮVODNÍHO clusteru:
    name: n8n-db
