---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-smtp-auth
  namespace: n8n
spec:
  encryptedData:
    SMTP_PASSWORD: AgB7xfQfHi1X9g+oELJ9Z2mPIq+FNTue8it9kFblEBPJHNuw9IXuwaLTYB2ywBBZ4p1rN5kym0vxj5jE3PcKCHQHEG5J58OZ5zHvLDEmRFsfHe/0eD3x9UkHo7z4KHYkwn+7pbrA/bsnMLlzewc6muANrEn7NALiZ31JJ3lBYMH31Im+ekO/H1cuYe/JyUw+7N5DW0ubAf1OJGXQwinhjhOB2VD9/tuby+dQKxJcVSBV0+TlJ4Bo6XGAdjA6s82j+kCfl56qSOBM/7a1Q4/hy1hYuu1Ck/Cush2WPLnQY8J24xqnPUABde12Q+9u2Fwn2+Swdbe4tERBMLiWT3XYD7TlPxUsPKQM8w4mY5IKPDogi8dfO4Vg2Y73LlVuz0izaqmuN0bjNoHX1LarBF7Z2ias0UuvOEpEjAZ04nif1xgdBelAMi/I2j2MpAi2P6y1uX35lALA455Ah7NsS5czio6+CyDhonk5yKf83cGstKjBQknT2kjzFY+5iAPhs51KGxSSPv79IxGcVnKiMvtQXlJlrtnvmU/+QPRHuYY83zclpNSxqWTL4k4sVg7Y0YZWdqilEK9Xk1DKeuehJtdPM3+GAsgvDVvYpg5MFQf8IyAYuqw1rxEOl5MBiboVi7Kq9kZDGaoQRoSsHfrO+RuuStGwX1bp5I5dpp3gqQdoQmhKTE15vfWFGlrcFONr+Va3tKfyofUJZ81pqMoYidpPW32gwc3hpQ==
  template:
    metadata:
      name: n8n-smtp-auth
      namespace: n8n
