---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-backup-s3
  namespace: n8n
spec:
  encryptedData:
    ACCESS_KEY_ID: AgApwQ2GfXYvIdEd1fpDSQ3/QadWvcffNGLeFevRGrowzbp7btoJgg3DfD+GDoJa2ueNmXcWxE+L3kkMxhx2Zy2JVY6/04aEQH/I1R8LMxW6c7K5Pq5d06Bf2Blgggsnb2oFxD8OwIsETZ4jR0vsnadwUdo0hzwM0LwBLaPYa8UzIG6Hx2VW4BbiPv0yqigVBeGEU9AhN9ksXYNShN6CrdzfG3iKUUd0XKSzULdeh4HXaNOwQojwM/eNk7GtETBiHZQZRQm7PZadRWC8yrRw9aDk+89BycCsBOe2RIb+QDp+CmdjtKBJsZZ6BB0CAa3DiladtOZcQ/fAzKKIXYxuIZV/tuf+1PnI/d60DNHB3lWxLHWRaSY/M5c2fzxO3ZrsfKK6sVv8A8c2TEXfVXO8/QnTw+sDRPhoksIz2zqS2ffBXPmDgrr5lT48d7qnEv93zlTcKEr+oJs4Myg3mlikZj9CxKAOeAVGCD3hfAJ69HtCpb6nfLecEqBQjjUm9pCZTsZyG3B7cJteLbnv+wJnE+7+H3EWvCyEijYprc2jqjFLJMpbA4LtxTK3mMOCt+K5JNrw2m/aGeNwBRbjcc7nTStO+0rPpBHy/7rTTT8MfdX4BgCTF/w41H2NtNpRSVB8961JH2kvEO01xocfX+sHmu/6USy0YB3VUnet/nj52c3yVdmTMQvslhAzb9ARhJ/FLeAVzgQ9a2FCOW5uVo8vdA2chFopTw==
    SECRET_ACCESS_KEY: AgC/SMyRy5HFtFa0c5BHu2MAkX58YK34jUciHuWniOD2saX16F/GVi/bemkVrHrp/5h/9MrXKxfytV1J/XlSFjo7cRUH7WJeWlhvD2s45mOLtO7HCFzkfyRbzvNxXA8280wmjTGjjNvXqc4qAr45lXZ+SPaLIqV7PTuTsCBbcbjuNx9h5rs7p479aQ0YSZUJ+Y65x+goCzEBRxvyeoW+hLovpz55z6RSSAtExeFUgipc2BPnDXE9+6qnGusa4fgyrJdoN+omch+I2/aIg/5IdrtJwGj6+MT8MTmNHZDtLpgByuaij+FXIAkIBvSXhk5Ia7BRfPsvQJ1SN3Zhyn6PGRH2+dLKg0pcCvgxwRM2yaS/hTAZb9BxPS4xFuOdtU5YZEPcltwNK4IkL3ieuOy/V2fg8cY6xybRcub+JNNCwywA7EIzAhsl6Fn9AKxS7pbezgJ02FmlYganqqVr6FH1jayGxi2vEKcGnywDdokAnK/uoVRSSa+Zf5q61odpAgHtDRQB7a+kSr8jdpE+Gi54Wz8RlWf9U3j3pyRjYw/wXYME4wniLDgOtjStQoE9S8V0+Pcmz9mG6Z07zffY2CFtZKSxEpjY74smgziBHBsSww6vIDZfCyiIsJDhBfH9Ec4mkS/LtkGvihNuI8217GK8d3Tb/oAQZYTlYu7D02nn8LF7NJEsfR2zu446XMUAxNDGLnVQ1eGa0TVsu8F2ArnaQ/xTSkEYoQ2OWsSfXS60Zj2QP4ZnbX+tENSH
  template:
    metadata:
      name: n8n-backup-s3
      namespace: n8n
