---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-db-encrypted-user-secret
  namespace: n8n
spec:
  encryptedData:
    password: AgCHeRFZfO/fzjWEYQLY+VowMWs5aVkuPyZNevKEvIUhjBUCpwkxqhjSwkGaKdUu0bcup3INvyZiiTxp3s/wcDlhL304mocsqO9Oc9BeOsGGQ9mPqnzpvUYNTJxQfI+o1IuCVIFUlFNvIQOmH7BbwXGLj1mo8gJuGNTKWZeLmyvTTZ87Jw33IAJ0vJMqrYcLyZW5GRRD6EQJ1nDGwAUQytXUa1qQ19ywcMOZyVNgLx8xWKaEyr0vPhFZiN5l8RQ7W4pgi99XaLGawvU+jLgF62fYCv3JZJYKGubYj6gedj0p31gKOlELCoDofD+4sNFC3NZN3rXrp8We0SNN/WCkW+UGdwdHI0IiRkXXsoMOy8cyPOOAW32HPUMV5Be04mL2C90lNbasYZJHXGYgSIel/1MHh/0Fhi1sDfyy0h3M0mX+4y62E47+vmmMLcX/QxD9yNEOBZf0+WKmsovcl00peMfZl+2L+EMColZY5EXUynwOPIRd7ptyzTdE2iAXFWQJwmfKY0uiN/4Q1TK5Tk/kLDRe69QwwodGDkvcP/tvrItiIXLNk5X+Zf0o6HmqN0r5lbSXQfqg23Zurn+xDLwaYxYEt0jaWxTyVlLAkyNsclPZROD0kHlVwScYlwDG/vJc/N/SRGjq4MoSd1Iq7UOLC1k3pqCS1tKbFHvDmPaaWj9zGZCjxaoxibdiFZ3skBqT6qgejYrT1QIehpNdwhGA+/UuJiEg/7+D/Uwu6DXokR5OQh+ooDBdPzOQJw+fbqd1gAMdPrZ8RvjekxBBaZSk0ofD
    username: AgCHF21dimY1Owz7/cUEscYeeLAkHUCuMBGFOaFfHnd7Mtk22sNGeXNQWS055QPFA/7tAYdNKfbIIPqGYglZc4QkHL3bCtvrCLpoplDSxbC8uzaPe+RDebRHjGT82vT/fJC1jH6liGOGsavfIgnEhijJodpG6qD+GHRT0Eb1H+erG/dvRhHQn+tLfTBmsnKBZXxO//LiHEY9xExcKy3z8MSE7wJX6kWnJ74sc03fuDFsDWcrvrc0zlvAIbAxbFXLD3vVOHlbY4hYq4kYLVfz/JfFsoh9NMqTRfnk7HN1wWs3LxOoycVU6H66B1lNILVKqg8Ea0wzpN3cmwbB01uQWVrsF1AUynC8bnEGRA+Lq/akJfRBk+PCKFzvjf/ngJgtJftCJkGZXR9ljXC7DWMe35nsEeXAReDMyrLK1ESW6TerdC3YwTulDksHiXhln/BJZ08TD69k68a1aAHPERc5TAH+N0fY7Rcn5CUaosNrr6PDAW6Y6jZ9GxGCwytYcm14TMxW+sIJcsGJqggKxysYg4B5ERAs3J9Karwi4EByhm3AnzbAJXLRFdanJP/yGv+hyMONiKWmaAa9zRE/FUUhdhDE0w+hr76qJzmFQH4Um31X6NmvMcyKUVe6P8Azingai+BXiKqzkNM51i4T4NJIYBlCgbgkI/34rC81o1rFRb+u5Iwyg9feyjWq0//JLCAt7aUao9E=
  template:
    metadata:
      name: n8n-db-encrypted-user-secret
      namespace: n8n
