apiVersion: v2
name: vikunja-wrapper
description: A Helm chart wrapper for Vikunja (official go-vikunja/helm-chart) with CNPG database
version: 1.0.0
dependencies:
  - name: vikunja
    version: "v2.0.2"
    repository: "oci://ghcr.io/go-vikunja/helm-chart"
