# Tuwunel (matrix) server
image:
  repository: "ghcr.io/matrix-construct/tuwunel"
  tag: "v1.9.0"

ingress:
  host: "matrix.mracek.dev"
  className: "nginx"
  clusterIssuer: "letsencrypt-prod"

storage:
  size: "10Gi"
  className: "longhorn"

tuwunel:
  serverName: "mracek.dev"
  allowFederation: "false"
  allowRegistration: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi

probes:
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
