---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-dev-user-secret
  namespace: postgres-dev
spec:
  encryptedData:
    password: AgAY/4Xc7VApgaediWg/VMQwy/q+jcTT7a1cPlLkYWazE/KadpU0BQsitiNl1xsu4+f715RRIXWEf9MHi1vc9KDLhvxEWSBHZq4WzkXW4Ujl7GE3V7j6YA9g/ge9Oc5o8u174bNbNWyJtQPRIxm3veGP2KajgLimnnnF3QYwUZjaRQWn0tpinlZeN4X1sVtMZeJwZKqJm2PodmefEGnWhIxJ1ZoKsR5In0wOegyVo5PSHRly2qM6oj84UPyoKka5/Hf9+HEbR5znrRNqrTLKATBUnprzdagJ0lDtFJLAj5zRJffiId87MM+vf2HP8nm1BMuqHFDFrSiT4IHCeJwi8NUeQrQR962cZNc/G0yyrOprPE0okV7qRhWbvXy20kSFKcXf81C6ySygJ3VWdqAqNN3qlOMU27eY2IXFYfZgxF7k5OHeL5CUuTVVGApAF85Gwu90WpZbghTQPzCM/lrWHJYM4KaNprcc3zJA4z2w+oWzEscqGesn2JobBekOHDn4zGysTfXth1uRF+3GuZByk2egs6ifPkmtrfSogjzey/SEL5mmlyLucJ5+rQojPmqCTd/OibMr5ZpGj4c3jsqg6z0BNyHV/uAOnfbSoIdPWWK1JT6HK3oQvRFC0CW3CffCLqe4EARoqXnJT18ELogbZBkU6hgFjj4AL8C/h1kurligYwyTwhjKGxNr0d0i8kKEaB5e5nrAsdPxbyGLhdL/MJUyqz0q5DRCA3h/sORIzAo=
    username: AgB60oUl/kWb53aCZmvVeOJMX2tfrSEZWG448c237b2zwkhS204kcvHETxWUbPALqgt91aIgXsEwFXjzhb6GXvAPG+qBSERc6EH+NMzgvpAt4jAQlWQrGouFpivEbRe7T0CXxgBsMvPhHMponssvpdWzj7tejy7rHD0tmT8ofqCIk614slNtkHMpyqYZ8c8vL/8idRxfJhMNT1JfiOHwRr7gTFMFWp56/6Saluldsg+5ZNqJHIZWzpi774MHEWNbzmz2/yfDWw4Zs1+Nvf/3hjXP6c5U/iwnL/TD554LZalK9jAH3Wqr/1GCeQZrEe0bd7UYKZQvFG6U17kcTSw0VBMgUmv5ZNQA0i9RvmvinPuCo6IdcQfZ17IhfyCA1Cy7BWMwlOEh7JsFP56RMo4I6VeeL2RCyQg7GbCkE9vTnKiJPzm14v43p4qp72UL7HTYv15o9w643grvMvCSvqTROIVA/dTG2QqDWuWouSHTVv9l7fuJX40pBDy3X5OvT/YqU8omoh4wubDJWkEelFvRTkGCmKr2grj2WS6gYsRuD5YoMkcfYmBwAspUcfOE4KQTil382Ky0QDSMqrOOZpIKaSSTR2dIfSaG7tLo0edh9I1jk0QSHflpP9UovzgDbSECWD6IL3gg3oNa8LT0U2AMRJHJHACm0KbZjCMjfNZ1aCye6pweCwZBasaYsji7VpztEJfJmJngI6QJ
  template:
    metadata:
      name: postgres-dev-user-secret
      namespace: postgres-dev
