kube-prometheus-stack:
  kubeEtcd:
    enabled: false
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorSelector: {}
      ruleSelectorNilUsesHelmValues: false
      ruleSelector: {}
      secrets:
        - etcd-client-cert
      additionalScrapeConfigs:
        - job_name: "talos-etcd"
          static_configs:
            - targets:
              - "10.10.10.11:2381"
              - "10.10.10.12:2381"
              - "10.10.10.13:2381"

  defaultRules:
    rules:
      kubeScheduler: false
      kubeControllerManager: false

  # Grafana za Tailscale
  grafana:
    admin:
      existingSecret: "grafana-admin-credentials"
      userKey: admin-user
      passwordKey: admin-password
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - grafana.mracek.dev
      tls:
        - secretName: grafana-tls
          hosts:
            - grafana.mracek.dev
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"

  kubelet:
    enabled: true
  nodeExporter:
    hostRootfs: /rootfs
