---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tuwunel-secrets
  namespace: tuwunel
spec:
  encryptedData:
    registration-token: AgBJE6wESnQmxQo413rr4wFOZG7qDiTZE/p/MQiPYTP39mpwsQQH4ZAWOYfPW9pJ5bcQBhSKF5vNLCktPrht455HsPZaJblG5t8Yjq5j5+oB/6Zuczdwz/iTFaJBLFlNZv0e7jysO4+RSQXCDT4NJUB2ENfCB+raV3cKMB94XejhqfoWzQvDn9ei4hN7ch0NRsMjAQc8DW3vdp6CNScJNuzjC5vt5X8meYjerg8zatYmgUBdbnOdzoCr7yNvE+Z2Y89yKxJxRJEK36AzgKi5MYUBKYuH+hXeUpoU0soQ6P5UcvPLfTr2P/naNQlnfXohgFTq8s73rDkYrXxZNfyYIiEYT24srTuJBSuyugLodcOP/oqgM4M+kOHbQRVYVf5VFImux5wdYKuQi3HBfud+EG6Q0tFKxYcoFgvKwB1Th8TN3JI0ww1B5elNJRUYI0xj1z7FoCdJpGmZQNWiAnBFleytP69fpTM/8f74+kSxZzyJ4mbstXrGk9l3ZlZ+eFJS7Gp2zoIYsCOvuQX9eVkT2825UABr1PNBTzPu6jRVNjuRSSKX9vg8oc9Woz2+WA1KeDc7L8YOT1kj2dlT44wBj9M/kyEK6KyfHdYixnvf2a8/LGlrGaDjvKvS9DeQkg0sdzj2nYTk6JpP/ZDCq7uBqq0Z7WmZ3BictyLBw7dtc3Eb97cDYXlowZI4vzav1RFBWKRG0XLsRrlJPrX+oTY/7oE9kJ6SyAxtLxU/LC3koWVMfOVyIwTAPM31gvNqtRl3MzvtEZy6EucF7T8eGLF0UOSj
  template:
    metadata:
      name: tuwunel-secrets
      namespace: tuwunel
