---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-s3-creds
  namespace: tuwunel
spec:
  encryptedData:
    ACCESS_KEY_ID: AgALCTbzteOTkGSLNhulOXI8Qn2goOvruDHCEHlZEE6CLjn4g81cHXwOS/z6PIlrkJZ0SlvUNEZBK9Komka3xUSPHCPwXm1uOCRrt1FTpA/ErN1jHtkSpFZGiIcM89oFYSXRl4SHpO4TtFjig/+HD9mSiM3WrQu6LnsWE8YoVBtwjiYuciupQZn/fHXbhgfM7Nyetsm8IYBYOMJqbtjOI5TQ2wqK9BHNpSBm04NfbY/FASPJ5PIZUKlUMpN07VfwW7IQ4KrYFjKuVE+uaGWVUeoeqjcbU26V2woBEjbHqxXCBWaIIQXleGompGtnxCX+JnoV3XGpqQQUub8Pmsx2hcxXoND0EReIPdHwUj/GyuHXgpUztGTXjnp8cPpfiVfj0ttcobUOmZ6hbrq/zls3Kr81V9G35mQYUQImgy5NSYGiU5MwI0Cq0a3n1sUvnwn/34Etx5pdHgf5fjjiYCnIEVwhRvRifx4MZkkh2BH2UUor1DVqKOzyyyDNv3Nr+v9Ql2dDXMimL8OnaHvUH8J8mUpVcar08fz67uZrakhfUuGCfLdih1mm4JmAGIdvfyoBJoGVRijOWWTNARx6AucZLNAs5598tQ3LzOBB1rUhlaCESgQdJddDDFCNTr7fFERy13N3tSzcAb3NgmFW53EgejROt5qvr0uAnkiZ9lTxeOGq0sx/bIBxBFx1uICur7I8E0Sj745psyLYMrz+PnLUVoE1Qn3KJQ==
    SECRET_ACCESS_KEY: AgAMS5g2TmakJ1ekXkqbrmbmlo+r8R/E9RojbZGrEhlcdbKPaSx5aLEmVFeMuqIXVPRfUd+EMc8yUrULdby+amWysAmfXRIBCDqwp0TrCJlbCsNyIw5p/9LP24j/WZUXXKuGyLGzOfzB2OEvuZmwBN4jNZNYCUZLXDcd1uP+dSfcVpHM+l2V2cDcm+yOkYNtjAWsUU9tqrdG+Hj7J09X60p2/NEI4UqSvPr9if2p5RKrNWLXSNf0I7qq0ldPab2QFJDyOlBkiqSrw3P5nYyBtItExMA9QrDQ8XxHHL6M8AUW5eUz48GMfNEJNDzTzJjuUle9M5J3x6NNvo0t/q1SoS+itfIJDat8Zy/QMZakxk79yEtzDcVd34vhnbza6QRxlNHpfIWydXO+KfvGNZR7np4w6aPfUqSogXhG4xnujl0MOVP84ts9/ye9mNO3cNNWSftPn1OznOY5meSDThRkA9rikhW9yw11GcyR20PC+wrt1wr5uUVxWtmxKTrEBxyUBH+DNnsI39gXRbi64Q/qRtkX8j1thX7+9eGZZRj7bqbXD8GR+ilfKF/KP/D9kXGfcsIi/J4/nBd0h74g+kdP3D9SSzh7D5rKgW5QSydCOFh3qVe8g0IhT1b/KpP5V68C2fLPvUKBeypNvsdXbs/DPKAsHVWaFG33d1SWM/bIgDhY+PyoIOMcAxfKTfEA5t7HtoGguYtcN6cw7g4F0mg/zUix35a70yC7QwAIaEpLeVxnCq2R8jSirl8f
  template:
    metadata:
      name: hetzner-s3-creds
      namespace: tuwunel
