apiVersion: v2
name: longhorn-setup
description: A Helm chart wrapper for deploying Longhorn distributed block storage
version: 1.0.0
dependencies:
  - name: longhorn
    version: 1.11.2
    repository: https://charts.longhorn.io
