image:
  repository: "docker.n8n.io/n8nio/n8n"
  tag: "2.27.2"

ingress:
  mainHost: "n8n.mracek.dev"
  webhookHost: "webhook.mracek.dev"
  className: "nginx"
  clusterIssuer: "letsencrypt-prod"

storage:
  size: "10Gi"
  className: "longhorn"

storageEncrypted:
  size: "10Gi"
  className: "longhorn-crypto"

db:
  storageSize: "10Gi"
  storageClassEncrypted: "longhorn-crypto"

resources:
  requests:
    cpu: 250m
    memory: "512Mi"
  limits:
    cpu: 1000m
    memory: "2Gi"

probes:
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
