---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-runner-auth
  namespace: gitlab-runner
spec:
  encryptedData:
    runner-token: AgBiEdaLi/BMuBsa/3eDVXqWrqKWfDdGRE1bMWE1psnkT+0azTxIQrtiNw54xO6I0MDdORSTD9JS5KN6G3Wk/zyBBA0x6c8fD45A8yIcE0F3jhC2DGWSgTdrag+umUQhOIxpOUeWhZQCpAZZ30V2nFY/LitWvkXkJkKEcxzTHstHCtRkqDVbYXnH92RVtMT7OYQYkHT2uaVu20pFZqBxpuhDEi5kBlLMQREa8t0W0WSpMtfM4hTm3y0Xj4jsgs6lEmJ2xZDU17nIRNT99dmZTnvYdu2zUhucZeQ5VJcnJUwHawDz6vxSz5+cVpoRS12elPWUn5/H3fyJUnA/sJAcHAqB4NMyQmM8MobQr2EE0bOHvcOo01/xVUP9lfYl6IbSdgqZINl0c5JOlQTKqppVbtP3f14wYN+UbtVExIMP7EGR0p8sxcxascyTSUpo4f9sMWsxPdYwfAuDhMhS+LtggE1q3fse5xh4BtAYelIB8v6Zi5/9ZyjnribyYXepYCL8bXA6LNekGX1Tl3nptHSd8/0yYoipAqOQtw5LkYv5MOkKammBrFsIkbvL8oj0vkhQ8Q+0WJ6BiZnP1d3ik2es0Nji4G5RNYed5Qt8fZh53rVqtl9U9BTOzXt1D/6J1FlI9/02wwW+ssZEseCanmr0ct66TEjfd891KIyvBUaa8cHFBkG1pZwNowswRfINFlZW8PYNbBFqK8UTuJQauUYH5QBbUQtqke4JK1eAFFvuXAPDUJlMUOoM1TYZShY+BLy5Xvk1az7q71ui9Kq9lxH9LcKjX2aQiQ7KxYn8JAm5diU=
  template:
    metadata:
      name: gitlab-runner-auth
      namespace: gitlab-runner
