apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: kube-prometheus-stack-kube-etcd-custom
  namespace: kube-system
  labels:
    kubernetes.io/service-name: kube-prometheus-stack-kube-etcd
    app: kube-prometheus-stack-kube-etcd
addressType: IPv4
ports:
  - name: http-metrics
    protocol: TCP
    port: 2381
endpoints:
  - addresses:
      - "10.10.10.11"
  - addresses:
      - "10.10.10.12"
  - addresses:
      - "10.10.10.13"
