apiVersion: v1
kind: Endpoints
metadata:
  name: kube-prometheus-stack-kube-etcd
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-kube-etcd
subsets:
  - addresses:
      - ip: 10.10.10.11
      - ip: 10.10.10.12
      - ip: 10.10.10.13
    ports:
      - name: http-metrics
        port: 2381
        protocol: TCP
