---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBLUVG13UJyy/2RiKV3b8hQjjylGCgzQpt07lN1Zj/d5Ugqx26hTGgqeWp+VnQ9oArxJG58QoVYaj2peaTZGXr/urQy/JUiBQjqjZykb/sPdRnhu7S6hWXJVkh66V+YdtGlrv5lu2c7r+vY0jXkqEd9saq7mxoHLe8fM/ZtzZd3LRtvXYpZxMjBnbSAKTtCHEJMOv201jcOfbWZqHedFySXBWjUXBMyfxy7yO9qL5ZrFufDw+jQDrvPNiUqTsysMqUyg+GiIGFCPFIVgL/xyL+I3H6OIMebvRDGEOXdmGETUEuU4d71lRxEWQxv2XwedsK6Z9U60G17QU6T+b4WpTiVV6UQJDhHlMdAZ+2A9uN9OQ810RcFBelr4Cnmt37BplUGsLEDdYIVQdA5EDCpZqQTD6qxKgF3SUenx0ofQDIzQnxvohd6Z43EdTxyArNUnUE9k71gapnYw7j7yEoPlyGiG5dn9mQcR3qBQeJxPOhRUcy7n9wwvjS1cOUo7zv/eKAnG5aXdKZQV3XKILSVBBc9tZNia5qHHvDZV1QD34uk7MN8n9DY1CofPOSOmsXiLF+kdlyhfeuU0vXXYOOHcaXv4e4G38hdCM8Z5A29SOq8gqjZmkci2VqruENb9rnOnHTl4IZa4BCy8b3m9BxjJ6NYoqY0pykCFXXdlwGy9iRQZPcdW1HB/Qa5jdM+d1VNfvhAf+zNoEJH96Jgy16WPKLAfkI2lb7pf78wVZnqkUE=
    admin-user: AgBmuGqStYE3JTOpIQEPwjOwaysyDbMK79BRf4ojQF8YV7+MVULCTVa8i745Jf85xThlWpSSgXpc7ZsbYshi48NNupxzxFDtJ5lWJPi8Kx84Dz/Bndv/nyIj/YujJtwMfYzUy+/4hN1OaxdFBLpFHOcqB0hRxDY47UxB3Abpmd9n1YBtiruG7+pKgsv2kP7emWocTKELBXgHKhua6kiZ5Ol3KYv9OGqZtEpjNiOeQLfD+6hq/irhR4LlcBOr9ZpND9RFjz6BbXggD8DYueyBoQpVYUpaXe8MmFFvwiQ9E62z9U7X9BLpbTmzFmkunGj5A+d7f6lU/LsyrsKZsN3FKaEp6VZI2P6fL+L20Vjn4npHzCogOVfI0jGZNxSvpZ4mbs7toSEA3ewao+kfJ8JpFOYkPm6Obg8I7XW8lqGFopbikD2cRYP/XTjass+B4HBcs+V+j9tH+t9NWd6H4j5dmBvUZA7XcV9aDUpNDZeO+DqIb3SEjQXv92KAOEs6nxbLjCPmfZZeDm3EjN5fBVRQgDDQlFbDcQrzPWUNfDERn7d+iGiuECnkkTkrJCTHJ3GNZfN8X0d08hudApWO3soWZUhv1Tkmn5PXZnKQceWarQCKiompxoI5L55s5yP3EYOr2l75Ar9l0BUO7pgDXXYEd+JWypbeSTLLj6Ju0pwPM48zunIj5+wFfrh+f7/zwdZce8oEj2sruA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
