apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opnsense-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'git@github.com:git-mracek/talos-gitops.git'
    targetRevision: main
    path: charts/opnsense-exporter
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
