apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
    - group: postgresql.cnpg.io
      kind: Cluster
      jsonPointers:
        - /spec/managed/roles
  project: default
  source:
    repoURL: git@github.com:git-mracek/talos-gitops.git
    targetRevision: main
    path: charts/postgres-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
