apiVersion: v1
kind: Pod
metadata:
  name: mover-n8n
  namespace: n8n # Uprav podle tvého namespace
spec:
  volumes:
    - name: vol-old
      persistentVolumeClaim:
        claimName: n8n-data # Staré nešifrované PVC
    - name: vol-new
      persistentVolumeClaim:
        claimName: n8n-data-encrypted # Nové šifrované PVC
  containers:
    - name: mover
      image: alpine
      command: 
        - "sh"
        - "-c"
        - |
          apk add --no-cache rsync
          echo "🚀 START SYNC APLIKAČNÍCH DATA N8N..."
          rsync -avz --progress /old/ /new/
          echo "✅ APLIKAČNÍ DATA N8N HOTOVA!"
          sleep 7200
      volumeMounts:
        - name: vol-old
          mountPath: /old
        - name: vol-new
          mountPath: /new
